version: "3"
services:
  db:
    container_name: storage_db
    image: postgres:14.5-alpine
    ports:
      - "35432:5432"
    env_file:
      - .env
    networks:
      - storage_net
    restart: always

  api:
    container_name: storage_api
    build:
      context: .
      dockerfile: dockerization/Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    networks:
      - storage_net
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - storage_net
    restart: always

networks:
  storage_net:
