version: "3"
services:
  db:
    container_name: storage_db
    image: postgres:14.5-alpine
    ports:
      - "35432:5432"
    env_file:
      - .env
    networks:
      - storage_net
#    restart: always

  api:
    container_name: storage_api
    build:
      context: .
      dockerfile: dockerization/Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
#    entrypoint: alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000
#    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"

    networks:
      - storage_net
#    restart: always

networks:
  storage_net:
